name: TheArtOfMx
favicon: null
layout_spectrum: 0.8684208581689745
typography_spectrum: 0.4236704132054001
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#808080'
    - '#810102'
    - '#c6c6c6'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.20521204522810876
purpose: []
